# Generated by Django 3.0.4 on 2020-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uttu_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name_of_car',
            field=models.TextField(default='debny'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='name',
            field=models.TextField(default='sami', max_length=20),
        ),
    ]
