# Generated by Django 3.0.4 on 2020-03-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uttu_1', '0002_auto_20200311_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_pizza', models.TextField(default='debny')),
            ],
        ),
        migrations.RenameModel(
            old_name='Manufacture',
            new_name='Topping',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(to='uttu_1.Topping'),
        ),
    ]
