# Generated by Django 3.0.4 on 2020-03-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uttu_1', '0003_auto_20200311_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name_of_pizza',
            field=models.TextField(default='Pizza'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.TextField(default='Topping', max_length=20),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uttu_1.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uttu_1.Person')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='uttu_1.Membership', to='uttu_1.Person'),
        ),
    ]
