# Generated by Django 3.0.4 on 2020-03-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uttu_1', '0009_commoninfo_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='commoninfo_ptr',
        ),
        migrations.DeleteModel(
            name='CommonInfo',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
