# Generated by Django 3.0.4 on 2020-09-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uttu_1', '0024_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCroping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('file', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
    ]
