# Generated by Django 3.0.4 on 2020-09-18 18:43

import cropperjs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uttu_1', '0025_photocroping'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCroppingWithCropperJs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('image_field', cropperjs.models.CropperImageField(upload_to='')),
            ],
        ),
    ]
