# Generated by Django 3.0.4 on 2020-09-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uttu_1', '0027_auto_20200919_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryWiseBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdf')),
                ('category_of_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uttu_1.CategoryModel')),
            ],
        ),
    ]
