# Generated by Django 3.0.4 on 2020-09-17 10:02

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, upload_to=''),
        ),
    ]
