# Generated by Django 3.0.4 on 2020-09-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
