# Generated by Django 3.0.4 on 2020-09-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_remove_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
