# Generated by Django 3.0.4 on 2020-09-25 15:21

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_song_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='embed_video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
