# Generated by Django 3.0.4 on 2020-09-29 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='This is a title', max_length=255)),
                ('notes', models.TextField(default='This is the not ')),
                ('description', models.TextField(default='thia is decs')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('offer', models.IntegerField(blank=True, default=0, null=True)),
                ('time_added', models.DateTimeField(default=datetime.datetime(2020, 9, 29, 20, 24, 59, 338299, tzinfo=utc))),
                ('time_update', models.DateTimeField()),
            ],
        ),
    ]
