# Generated by Django 3.0.4 on 2020-10-16 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_testing', '0004_auto_20201016_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtesting',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 6, 57, 7, 46491, tzinfo=utc)),
        ),
    ]
