# Generated by Django 3.0.4 on 2020-10-17 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_testing', '0010_auto_20201017_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtesting',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 17, 17, 48, 57, 521808, tzinfo=utc)),
        ),
    ]
