# Generated by Django 3.0.4 on 2020-09-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
